languageCode = 'en-gb'
title = 'Adventures in SRE'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'


[params]
description = "Fermentation for the Nerd-like"
BookSection = 'projects'

[markup]

[markup.tableOfContents]
  startLevel = 1
